# Generated by Django 5.1.4 on 2025-01-25 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sigin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='image',
        ),
    ]
