# Generated by Django 5.1.4 on 2025-01-26 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigin', '0004_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
